# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0230af3a14aa54229229f2f62f26ca0f75b5b5e47a07f894414b265b9466fed4608af36d79ac30a3a8117a734db633edab38a98362fc8cf16a36f621840de7f5

test:
  secret_key_base: 60eb5736044b4e750785bec0f095a6d0c890a64b9bfe0b09ea584056b3a1f2da1c0aec736cbcb756fb017c07db1994af0905a85f868964b7d69b5d1ba99386b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
